Repository quantumlib/Qualtran, pull requests merged in 2023-11, with the labels that each got.

#461 Add rotation cost model
  qualtran/surface_code/algorithm_summary.py
  qualtran/surface_code/algorithm_summary_test.py
  qualtran/surface_code/rotation_cost_model.py
  qualtran/surface_code/rotation_cost_model_test.py
Labels: physical_cost

#463 Skip slow test configurations for slow tests
  qualtran/bloqs/qrom_test.py
  qualtran/bloqs/select_swap_qrom_test.py
Labels: devops

#488 Add `HammingWeightPhasing` gate
  qualtran/bloqs/rotations/__init__.py
  qualtran/bloqs/rotations/hamming_weight_phasing.py
  qualtran/bloqs/rotations/hamming_weight_phasing_test.py
Labels: gate

#494 Make sure jupyter notebook is installed in a dev environment.
  dev_tools/requirements/deps/dev-tools.txt
  dev_tools/requirements/envs/dev.env.txt
  dev_tools/requirements/envs/docs.env.txt
  dev_tools/requirements/envs/format.env.txt
  dev_tools/requirements/envs/pylint.env.txt
  dev_tools/requirements/envs/pytest.env.txt
  dev_tools/requirements/envs/runtime.env.txt
Labels: devops

#495 [autodoc] qualtran.bloqs.sorting
  dev_tools/autogenerate-bloqs-notebooks-v2.py
  dev_tools/autogenerate-bloqs-notebooks.py
  qualtran/bloqs/sorting.ipynb
  qualtran/bloqs/sorting.py
  qualtran/bloqs/sorting_test.py
Labels: docs

#490 [docs] Deferred maintenance on sphinx docs
  dev_tools/qualtran_dev_tools/reference_docs.py
  docs/bloq_infra.rst
  docs/bloqs/index.rst
  docs/conf.py
  docs/index.rst
  docs/reference/index.rst
Labels: docs
