Repository quantumlib/Qualtran, pull requests merged in 2025-04, with the labels that each got.

#1621 Greedy topological sort with symbolic register sizes
  qualtran/_infra/binst_graph_iterators.py
  qualtran/_infra/binst_graph_iterators_test.py
  qualtran/_infra/composite_bloq.py
Labels: bug

#1584 [open-systems] QCDType, CDType, QDType
  docs/bloq_infra.rst
  qualtran/Controlled.ipynb
  qualtran/DataTypes.ipynb
  qualtran/__init__.py
  qualtran/_infra/__init__.py
  qualtran/_infra/bloq.py
  qualtran/_infra/composite_bloq.py
  qualtran/_infra/controlled.py
  qualtran/_infra/controlled_test.py
  qualtran/_infra/data_types.py
  qualtran/_infra/data_types_test.py
  qualtran/_infra/registers.py
  qualtran/_infra/registers_test.py
  qualtran/bloqs/basic_gates/identity.py
  qualtran/bloqs/bookkeeping/bookkeeping.ipynb
  qualtran/bloqs/bookkeeping/cast.py
  qualtran/bloqs/bookkeeping/cast_test.py
  qualtran/bloqs/data_loading/qroam_clean.py
  qualtran/bloqs/data_loading/select_swap_qrom.py
  qualtran/bloqs/mcmt/controlled_via_and.py
  qualtran/bloqs/mcmt/ctrl_spec_and.py
  qualtran/bloqs/mcmt/specialized_ctrl.py
  qualtran/bloqs/mcmt/specialized_ctrl_test.py
  qualtran/bloqs/phase_estimation/lp_resource_state.py
  qualtran/bloqs/phase_estimation/qpe_window_state.py
  qualtran/bloqs/qubitization/qubitization_walk_operator_test.py
  qualtran/bloqs/rotations/quantum_variable_rotation.py
  qualtran/cirq_interop/_bloq_to_cirq.py
  qualtran/drawing/graphviz.py
  qualtran/drawing/musical_score.py
  qualtran/drawing/musical_score_test.py
  qualtran/drawing/qpic_diagram.py
  qualtran/serialization/data_types.py
  qualtran/simulation/classical_sim.py
  qualtran/simulation/tensor/_dense.py
Labels: qdatatype

#1627 Add small PNG version of the Qualtran lockup
  docs/_static/qualtran-logo-sm.png
Labels: docs

#1631 [2025-04] Dependencies, including relased version of pennylane
  dev_tools/requirements/deps/runtime.txt
  dev_tools/requirements/envs/dev.env.txt
  dev_tools/requirements/envs/docs.env.txt
  dev_tools/requirements/envs/format.env.txt
  dev_tools/requirements/envs/pip-tools.env.txt
  dev_tools/requirements/envs/pylint.env.txt
  dev_tools/requirements/envs/pytest.env.txt
  dev_tools/requirements/envs/runtime.env.txt
Labels: devops

#1637 Add graphics to be used in Qualtran API docs
  docs/_static/favicon.png
  docs/_static/quantum-ai-vertical.svg
  docs/_static/quantum-ai.svg
Labels: docs
